name: First Workflow
on: push
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - run: npm run lint
  Test: 
    needs: Lint
    runs-on: ubuntu-latest
    steps:
      - run: npm run test
  Build:
    runs-on: ubuntu-latest
    needs: [Lint, Test]
    steps:
      - run: npm run build
